# Pandas 한번에 제대로 배우기




---



In [2]:
import numpy as np
import pandas as pd
pd.__version__

'1.2.4'

## Pandas 객체


### Series 객체

In [2]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [3]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s[1]

0.25

In [6]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [7]:
s['c']

0.5

In [8]:
s[['c', 'd', 'e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [9]:
'b' in s

True

In [10]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=[2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [11]:
s[4]

0.25

In [12]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [13]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
s.value_counts()

0.00    1
1.00    1
0.50    1
0.75    1
0.25    1
dtype: int64

In [15]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [16]:
pop_tuple = {'서울특별시' : 9720846,
            '부산광역시' : 3404423,
            '인천광역시' : 2947217,
            '대구광역시' : 2427954,
            '대전광역시' : 1471040,
            '광주광역시' : 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [17]:
population['서울특별시']

9720846

In [18]:
population['서울특별시' : '인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [19]:
pd.DataFrame([{'A' : 2, 'B' : 4, 'D' : 3}, {'A': 4, 'B': 5, 'C': 7}])

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [20]:
pd.DataFrame(np.random.randn(5, 5),
            columns=['A', 'B', 'C', 'D', 'E'],
            index=[1, 2, 3, 4, 5])

A         B         C         D         E
1 -0.475097  0.153538  1.167551  1.870953 -1.030394
2  0.191699  0.968959 -0.655110  1.598391 -1.447329
3 -2.957880 -2.698595  2.262150  0.630355 -0.387836
4 -0.874204 -0.351303  0.791829 -0.139447 -0.206368
5 -0.306700 -0.196562 -0.962519  0.232477 -1.194005

In [21]:
female_tuple = {'서울특별시' : 4988571,
               '부산광역시' : 1735805,
               '인천광역시' : 1470404,
               '대구광역시' : 1229139,
               '대전광역시' : 736599,
               '광주광역시' : 734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [22]:
male_tuple = {'서울광역시' : 4732275,
             '부산광역시' : 1668618,
             '인천광역시' : 1476813,
             '대구광역시' : 1198815,
             '대전광역시' : 734441,
             '광주광역시' : 720060}
male = pd.Series(male_tuple)
male

서울광역시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [23]:
korea_df = pd.DataFrame({'인구수': population,
                        '남자인구수': male,
                        '여자인구수' : female})
korea_df

인구수      남자인구수      여자인구수
광주광역시  1455048.0   720060.0   734988.0
대구광역시  2427954.0  1198815.0  1229139.0
대전광역시  1471040.0   734441.0   736599.0
부산광역시  3404423.0  1668618.0  1735805.0
서울광역시        NaN  4732275.0        NaN
서울특별시  9720846.0        NaN  4988571.0
인천광역시  2947217.0  1476813.0  1470404.0

In [24]:
korea_df.index

Index(['광주광역시', '대구광역시', '대전광역시', '부산광역시', '서울광역시', '서울특별시', '인천광역시'], dtype='object')

In [25]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [26]:
korea_df['여자인구수']

광주광역시     734988.0
대구광역시    1229139.0
대전광역시     736599.0
부산광역시    1735805.0
서울광역시          NaN
서울특별시    4988571.0
인천광역시    1470404.0
Name: 여자인구수, dtype: float64

In [27]:
korea_df['서울특별시':'인천광역시']

인구수      남자인구수      여자인구수
서울특별시  9720846.0        NaN  4988571.0
인천광역시  2947217.0  1476813.0  1470404.0

### Index 객체


In [28]:
idx = pd.Index([2, 4, 6, 8, 10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [29]:
idx[1]

4

In [30]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [31]:
idx[-1::]

Int64Index([10], dtype='int64')

In [32]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [33]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산



---



In [34]:
idx1 = pd.Index([1, 2, 4, 6, 8])
idx2 = pd.Index([2, 4, 5, 6, 7])
print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx | idx2)
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2)

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 5, 6, 7, 8, 10], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


<ipython-input-34-1549881258cf>:7: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  print(idx1 & idx2)
<ipython-input-34-1549881258cf>:9: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  print(idx | idx2)
<ipython-input-34-1549881258cf>:12: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  print(idx1 ^ idx2)


## 인덱싱(Indexing)

In [35]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
             index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [36]:
s['b']

0.25

In [37]:
'b' in s

True

In [38]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [39]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [40]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [41]:
s['a' : 'd']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [42]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [43]:
s[(s>0.4) & (s<0.8)]

c    0.50
d    0.75
dtype: float64

In [44]:
s[['a','c','e']]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [45]:
s = pd.Series(['a','b','c','d','e'],
             index=[1,3,5,7,9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [46]:
s[1]

'a'

In [47]:
s[2:4]

5    c
7    d
dtype: object

In [48]:
s.iloc[1]

'b'

In [49]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [50]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [51]:
s.reindex(range(10), method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [52]:
korea_df

인구수      남자인구수      여자인구수
광주광역시  1455048.0   720060.0   734988.0
대구광역시  2427954.0  1198815.0  1229139.0
대전광역시  1471040.0   734441.0   736599.0
부산광역시  3404423.0  1668618.0  1735805.0
서울광역시        NaN  4732275.0        NaN
서울특별시  9720846.0        NaN  4988571.0
인천광역시  2947217.0  1476813.0  1470404.0

In [53]:
korea_df['남자인구수']

광주광역시     720060.0
대구광역시    1198815.0
대전광역시     734441.0
부산광역시    1668618.0
서울광역시    4732275.0
서울특별시          NaN
인천광역시    1476813.0
Name: 남자인구수, dtype: float64

In [54]:
korea_df.남자인구수

광주광역시     720060.0
대구광역시    1198815.0
대전광역시     734441.0
부산광역시    1668618.0
서울광역시    4732275.0
서울특별시          NaN
인천광역시    1476813.0
Name: 남자인구수, dtype: float64

In [55]:
korea_df.여자인구수

광주광역시     734988.0
대구광역시    1229139.0
대전광역시     736599.0
부산광역시    1735805.0
서울광역시          NaN
서울특별시    4988571.0
인천광역시    1470404.0
Name: 여자인구수, dtype: float64

In [56]:
korea_df['남녀비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'])

In [57]:
korea_df.남녀비율

광주광역시     97.968946
대구광역시     97.532907
대전광역시     99.707032
부산광역시     96.129346
서울광역시           NaN
서울특별시           NaN
인천광역시    100.435867
Name: 남녀비율, dtype: float64

In [58]:
korea_df.values

array([[1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [           nan, 4.73227500e+06,            nan,            nan],
       [9.72084600e+06,            nan, 4.98857100e+06,            nan],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02]])

In [59]:
korea_df.T

광주광역시         대구광역시         대전광역시         부산광역시      서울광역시  \
인구수    1.455048e+06  2.427954e+06  1.471040e+06  3.404423e+06        NaN   
남자인구수  7.200600e+05  1.198815e+06  7.344410e+05  1.668618e+06  4732275.0   
여자인구수  7.349880e+05  1.229139e+06  7.365990e+05  1.735805e+06        NaN   
남녀비율   9.796895e+01  9.753291e+01  9.970703e+01  9.612935e+01        NaN   

           서울특별시         인천광역시  
인구수    9720846.0  2.947217e+06  
남자인구수        NaN  1.476813e+06  
여자인구수  4988571.0  1.470404e+06  
남녀비율         NaN  1.004359e+02

In [60]:
korea_df.values[0]

array([1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01])

In [61]:
korea_df['인구수']

광주광역시    1455048.0
대구광역시    2427954.0
대전광역시    1471040.0
부산광역시    3404423.0
서울광역시          NaN
서울특별시    9720846.0
인천광역시    2947217.0
Name: 인구수, dtype: float64

In [62]:
korea_df.loc[:'인천광역시', :'남자인구수']

인구수      남자인구수
광주광역시  1455048.0   720060.0
대구광역시  2427954.0  1198815.0
대전광역시  1471040.0   734441.0
부산광역시  3404423.0  1668618.0
서울광역시        NaN  4732275.0
서울특별시  9720846.0        NaN
인천광역시  2947217.0  1476813.0

In [63]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

인구수      남자인구수      여자인구수        남녀비율
대구광역시  2427954.0  1198815.0  1229139.0   97.532907
부산광역시  3404423.0  1668618.0  1735805.0   96.129346
서울특별시  9720846.0        NaN  4988571.0         NaN
인천광역시  2947217.0  1476813.0  1470404.0  100.435867

In [64]:
korea_df.loc[(korea_df.인구수 > 2000000)]

인구수      남자인구수      여자인구수        남녀비율
대구광역시  2427954.0  1198815.0  1229139.0   97.532907
부산광역시  3404423.0  1668618.0  1735805.0   96.129346
서울특별시  9720846.0        NaN  4988571.0         NaN
인천광역시  2947217.0  1476813.0  1470404.0  100.435867

In [65]:
korea_df.loc[(korea_df.인구수 > 2500000)]

인구수      남자인구수      여자인구수        남녀비율
부산광역시  3404423.0  1668618.0  1735805.0   96.129346
서울특별시  9720846.0        NaN  4988571.0         NaN
인천광역시  2947217.0  1476813.0  1470404.0  100.435867

In [66]:
korea_df.loc[korea_df.남녀비율 > 100]

인구수      남자인구수      여자인구수        남녀비율
인천광역시  2947217.0  1476813.0  1470404.0  100.435867

In [67]:
korea_df.loc[(korea_df.인구수 > 2500000) & (korea_df.남녀비율 > 100)]

인구수      남자인구수      여자인구수        남녀비율
인천광역시  2947217.0  1476813.0  1470404.0  100.435867

In [68]:
korea_df.iloc[:3, :2]

인구수      남자인구수
광주광역시  1455048.0   720060.0
대구광역시  2427954.0  1198815.0
대전광역시  1471040.0   734441.0

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [69]:
korea_df

인구수      남자인구수      여자인구수        남녀비율
광주광역시  1455048.0   720060.0   734988.0   97.968946
대구광역시  2427954.0  1198815.0  1229139.0   97.532907
대전광역시  1471040.0   734441.0   736599.0   99.707032
부산광역시  3404423.0  1668618.0  1735805.0   96.129346
서울광역시        NaN  4732275.0        NaN         NaN
서울특별시  9720846.0        NaN  4988571.0         NaN
인천광역시  2947217.0  1476813.0  1470404.0  100.435867

In [70]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
             ('부산광역시', 2010), ('부산광역시', 2020),
             ('인천광역시', 2010), ('인천광역시', 2020),
             ('대구광역시', 2010), ('대구광역시', 2020),
             ('대전광역시', 2010), ('대전광역시', 2020),
             ('광주광역시', 2010), ('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [71]:
pop_tuples = [10312545, 9720846,
             2567810, 3404423,
             2758296, 2947217,
             2511676, 2427954,
             1503664, 1471040,
             1454636, 1455048]
population = pd.Series(pop_tuples, index=idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567810
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [72]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [73]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567810
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [74]:
population[:, 2010]

서울특별시    10312545
부산광역시     2567810
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [75]:
population['대전광역시', :]

2010    1503664
2020    1471040
dtype: int64

In [76]:
korea_mdf = population.unstack()
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567810  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [77]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567810
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [78]:
male_tuples = [5111259, 4732275,
              1773170, 1668618,
              1390356, 1476813,
              1255245, 1198815,
              753648, 734441,
              721780, 720060]
male_tuples

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [79]:
korea_mdf = pd.DataFrame({'총인구수' : population,
                         '남자인구수' : male_tuples})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567810  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [80]:
female_tuples = [5201286, 4988571,
                1794740, 1735805,
                1367940, 1470404,
                1257431, 1229139,
                750016, 736599,
                732856, 734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1257431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [81]:
korea_mdf = pd.DataFrame({'총인구수' : population,
                         '남자인구수' : male_tuples,
                         '여자인구수' : female_tuples})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567810  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1257431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [82]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.826153
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [83]:
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.826153   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [84]:
korea_mdf = pd.DataFrame({'총인구수' : population,
                         '남자인구수' : male_tuples,
                         '여자인구수' : female_tuples,
                         '남녀비율' :ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567810  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1257431   99.826153
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [85]:
df = pd.DataFrame(np.random.rand(6, 3),
                 index=[['a', 'a', 'b', 'b', 'c', 'c'], [1,2,1,2,1,2]],
                 columns=['c1', 'c2', 'c3'])
df

c1        c2        c3
a 1  0.060986  0.711096  0.409039
  2  0.046312  0.056353  0.535298
b 1  0.636762  0.542830  0.037306
  2  0.900611  0.064200  0.378392
c 1  0.442740  0.086773  0.546230
  2  0.366546  0.011517  0.238892

In [86]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b',' c', 'c'], [1,2,1,2,1,2]])

MultiIndex([( 'a', 1),
            ( 'a', 2),
            ( 'b', 1),
            ( 'b', 2),
            (' c', 1),
            ( 'c', 2)],
           )

In [87]:
pd.MultiIndex.from_arrays([('a', 1), ('a', 2), ('b', 1), ('b', 2), ('c', 1), ('c', 2)])

MultiIndex([('a', 'a', 'b', 'b', 'c', 'c'),
            (  1,   2,   1,   2,   1,   2)],
           )

In [88]:
pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [89]:
pd.MultiIndex(levels=[['a', 'b', 'c'], [1, 2]],
             codes=[[0,0,1,1,2,2],[0,1,0,1,0,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [90]:
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567810
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [91]:
population.index.names = ['행정구역', '년도']
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567810
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [92]:
idx = pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]],
                                names=['naem1', 'name2'])
cols = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]],
                                 names=['col_name1', 'col_name2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index=idx, columns=cols)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
naem1 name2                                    
a     1     -2.06 -2.51 -1.47 -0.61 -1.12  0.50
      2      0.03 -0.67 -1.38 -1.89 -0.31  0.64
b     1     -0.12 -1.53  1.43  0.35 -0.75 -0.96
      2      0.66 -1.60 -0.18 -1.12 -0.21 -1.76
c     1     -0.45  0.56 -0.06  1.37  0.47  0.46
      2      1.31 -0.95 -1.38 -0.32  2.07  1.02

In [93]:
mdf['c2']

col_name2       1     2
naem1 name2            
a     1     -1.47 -0.61
      2     -1.38 -1.89
b     1      1.43  0.35
      2     -0.18 -1.12
c     1     -0.06  1.37
      2     -1.38 -0.32

#### 인덱싱 및 슬라이싱

In [94]:
population['인천광역시', 2010]

2758296

In [95]:
population[:, 2010]

행정구역
서울특별시    10312545
부산광역시     2567810
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [96]:
population[population > 3000000]

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [97]:
population[['대구광역시', '대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [98]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
naem1 name2                                    
a     1     -2.06 -2.51 -1.47 -0.61 -1.12  0.50
      2      0.03 -0.67 -1.38 -1.89 -0.31  0.64
b     1     -0.12 -1.53  1.43  0.35 -0.75 -0.96
      2      0.66 -1.60 -0.18 -1.12 -0.21 -1.76
c     1     -0.45  0.56 -0.06  1.37  0.47  0.46
      2      1.31 -0.95 -1.38 -0.32  2.07  1.02

In [99]:
mdf['c2', 1]

naem1  name2
a      1       -1.47
       2       -1.38
b      1        1.43
       2       -0.18
c      1       -0.06
       2       -1.38
Name: (c2, 1), dtype: float64

In [100]:
mdf.iloc[:3, :4]

col_name1      c1          c2      
col_name2       1     2     1     2
naem1 name2                        
a     1     -2.06 -2.51 -1.47 -0.61
      2      0.03 -0.67 -1.38 -1.89
b     1     -0.12 -1.53  1.43  0.35

In [101]:
mdf.loc[:, ('c2', 1)]

naem1  name2
a      1       -1.47
       2       -1.38
b      1        1.43
       2       -0.18
c      1       -0.06
       2       -1.38
Name: (c2, 1), dtype: float64

In [102]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:, 2], idx_slice[:, 2]]

col_name1      c1    c2    c3
col_name2       2     2     2
naem1 name2                  
a     2     -0.67 -1.89  0.64
b     2     -1.60 -1.12 -1.76
c     2     -0.95 -0.32  1.02

#### 다중 인덱스 재정렬

In [103]:
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567810  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1257431   99.826153
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [104]:
korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1257431   99.826153
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567810  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [105]:
korea_mdf['서울특별시' : '인천광역시']

총인구수    남자인구수    여자인구수        남녀비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [106]:
korea_mdf.unstack(level=0)

총인구수                                                 남자인구수           \
        광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
2010  1454636  2511676  1503664  2567810  10312545  2758296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2947217  720060  1198815   

                       ...   여자인구수                                  남녀비율  \
       대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
2010  753648  1773170  ...  750016  1794740  5201286  1367940  98.488653   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                               
          대구광역시       대전광역시      부산광역시      서울특별시       인천광역시  
2010  99.826153  100.484256  98.798155  98.269140  101.638668  
2020  97.532907   99.707032  96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [107]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                 남녀비율  \
           2010     2020     2010     2020     2010     2020        2010   
광주광역시   1454636  1455048   721780   720060   732856   734988   98.488653   
대구광역시   2511676  2427954  1255245  1198815  1257431  1229139   99.826153   
대전광역시   1503664  1471040   753648   734441   750016   736599  100.484256   
부산광역시   2567810  3404423  1773170  1668618  1794740  1735805   98.798155   
서울특별시  10312545  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2947217  1390356  1476813  1367940  1470404  101.638668   

                   
             2020  
광주광역시   97.968946  
대구광역시   97.532907  
대전광역시   99.707032  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [108]:
korea_mdf.stack()

광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남녀비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남녀비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.257431e+06
             남녀비율     9.982615e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남녀비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남녀비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남녀비율     9.970703e+01
부산광역시  2010  총인구수     2.567810e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남녀비율     9.879815e+01
       2020  총인구수   

In [109]:
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1257431   99.826153
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567810  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [110]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

level_0      총인구수    남자인구수    여자인구수        남녀비율
2010   광주광역시   1454636   721780   732856   98.488653
2020   광주광역시   1455048   720060   734988   97.968946
2010   대구광역시   2511676  1255245  1257431   99.826153
2020   대구광역시   2427954  1198815  1229139   97.532907
2010   대전광역시   1503664   753648   750016  100.484256
2020   대전광역시   1471040   734441   736599   99.707032
2010   부산광역시   2567810  1773170  1794740   98.798155
2020   부산광역시   3404423  1668618  1735805   96.129346
2010   서울특별시  10312545  5111259  5201286   98.269140
2020   서울특별시   9720846  4732275  4988571   94.862336
2010   인천광역시   2758296  1390356  1367940  101.638668
2020   인천광역시   2947217  1476813  1470404  100.435867

In [111]:
idx_flat = korea_mdf.reset_index(level=(0,1))
idx_flat

level_0  level_1      총인구수    남자인구수    여자인구수        남녀비율
0    광주광역시     2010   1454636   721780   732856   98.488653
1    광주광역시     2020   1455048   720060   734988   97.968946
2    대구광역시     2010   2511676  1255245  1257431   99.826153
3    대구광역시     2020   2427954  1198815  1229139   97.532907
4    대전광역시     2010   1503664   753648   750016  100.484256
5    대전광역시     2020   1471040   734441   736599   99.707032
6    부산광역시     2010   2567810  1773170  1794740   98.798155
7    부산광역시     2020   3404423  1668618  1735805   96.129346
8    서울특별시     2010  10312545  5111259  5201286   98.269140
9    서울특별시     2020   9720846  4732275  4988571   94.862336
10   인천광역시     2010   2758296  1390356  1367940  101.638668
11   인천광역시     2020   2947217  1476813  1470404  100.435867

In [112]:
idx_flat.set_index(['행정구역', '년도'])

KeyError: "None of ['행정구역', '년도'] are in the columns"

## 데이터 연산

In [113]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    8
1    1
2    2
3    4
4    3
dtype: int32

In [114]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                 columns=['A', 'B', 'C'])
df

A  B  C
0  8  5  4
1  5  8  3
2  9  9  5

In [115]:
np.exp(s)

0    2980.957987
1       2.718282
2       7.389056
3      54.598150
4      20.085537
dtype: float64

In [116]:
np.cos(df * np.pi / 4)

A         B         C
0  1.000000 -0.707107 -1.000000
1 -0.707107  1.000000 -0.707107
2  0.707107  0.707107 -0.707107

In [117]:
s1 = pd.Series([1, 3, 5, 7, 9], index=[0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index=[1, 2, 3, 4, 5])
s1 + s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [118]:
s1.add(s2, fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [122]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)),
                  columns=list('ACD'))
df1

A   C   D
0  7  18   2
1  8   9  12
2  9  13  14

In [123]:
s1.add(s2, fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [125]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)),
                  columns=list('BAECD'))
df2

B   A   E   C   D
0   6  15  16   6  17
1   3  11  17   2  19
2  14   1  17  17  19
3   4   4  19  18  16
4   6   1   2   7  17

In [126]:
df1 + df2

A   B     C     D   E
0  22.0 NaN  24.0  19.0 NaN
1  19.0 NaN  11.0  31.0 NaN
2  10.0 NaN  30.0  33.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [127]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value=fvalue)

A          B          C          D          E
0  22.000000  16.222222  24.000000  19.000000  26.222222
1  19.000000  13.222222  11.000000  31.000000  27.222222
2  10.000000  24.222222  30.000000  33.000000  27.222222
3  14.222222  14.222222  28.222222  26.222222  29.222222
4  11.222222  16.222222  17.222222  27.222222  12.222222

### 연산자 범용 함수


#### add()

In [128]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[3, 1, 2],
       [4, 2, 4],
       [5, 7, 5]])

In [129]:
a + a[0]

array([[6, 2, 4],
       [7, 3, 6],
       [8, 8, 7]])

In [130]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  3  1  2
1  4  2  4
2  5  7  5

In [131]:
df + df.iloc[0]

A  B  C
0  6  2  4
1  7  3  6
2  8  8  7

In [132]:
df.add(df.iloc[0])

A  B  C
0  6  2  4
1  7  3  6
2  8  8  7

#### sub() / subtract()

In [133]:
a

array([[3, 1, 2],
       [4, 2, 4],
       [5, 7, 5]])

In [134]:
a - a[0]

array([[0, 0, 0],
       [1, 1, 2],
       [2, 6, 3]])

In [135]:
df

A  B  C
0  3  1  2
1  4  2  4
2  5  7  5

In [136]:
df - df.iloc[0]

A  B  C
0  0  0  0
1  1  1  2
2  2  6  3

In [137]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1  1  1  2
2  2  6  3

In [139]:
df.subtract(df['B'], axis=0)

A  B  C
0  2  0  1
1  2  0  2
2 -2  0 -2

#### mul() / multply()




In [140]:
a

array([[3, 1, 2],
       [4, 2, 4],
       [5, 7, 5]])

In [141]:
a * a[1]

array([[12,  2,  8],
       [16,  4, 16],
       [20, 14, 20]])

In [142]:
df

A  B  C
0  3  1  2
1  4  2  4
2  5  7  5

In [143]:
df * df.iloc[1]

A   B   C
0  12   2   8
1  16   4  16
2  20  14  20

In [144]:
df.mul(df.iloc[1])

A   B   C
0  12   2   8
1  16   4  16
2  20  14  20

In [145]:
df.multiply(df.iloc[2])

A   B   C
0  15   7  10
1  20  14  20
2  25  49  25

#### truediv() /  div() / divide() / floordiv()

In [146]:
a

array([[3, 1, 2],
       [4, 2, 4],
       [5, 7, 5]])

In [147]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [1.33333333, 2.        , 2.        ],
       [1.66666667, 7.        , 2.5       ]])

In [148]:
df

A  B  C
0  3  1  2
1  4  2  4
2  5  7  5

In [149]:
df / df.iloc[0]

A    B    C
0  1.000000  1.0  1.0
1  1.333333  2.0  2.0
2  1.666667  7.0  2.5

In [150]:
df.truediv(df.iloc[0])

A    B    C
0  1.000000  1.0  1.0
1  1.333333  2.0  2.0
2  1.666667  7.0  2.5

In [151]:
df.div(df.iloc[1])

A    B     C
0  0.75  0.5  0.50
1  1.00  1.0  1.00
2  1.25  3.5  1.25

In [152]:
df.divide(df.iloc[2])

A         B    C
0  0.6  0.142857  0.4
1  0.8  0.285714  0.8
2  1.0  1.000000  1.0

In [153]:
a // a[0]

array([[1, 1, 1],
       [1, 2, 2],
       [1, 7, 2]], dtype=int32)

In [154]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  1  2  2
2  1  7  2

#### mod()

In [155]:
a

array([[3, 1, 2],
       [4, 2, 4],
       [5, 7, 5]])

In [156]:
a % a[0]

array([[0, 0, 0],
       [1, 0, 0],
       [2, 0, 1]], dtype=int32)

In [157]:
df

A  B  C
0  3  1  2
1  4  2  4
2  5  7  5

In [158]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  1  0  0
2  2  0  1

#### pow()

In [159]:
a

array([[3, 1, 2],
       [4, 2, 4],
       [5, 7, 5]])

In [160]:
a ** a[0]

array([[ 27,   1,   4],
       [ 64,   2,  16],
       [125,   7,  25]], dtype=int32)

In [161]:
df

A  B  C
0  3  1  2
1  4  2  4
2  5  7  5

In [162]:
df.pow(df.iloc[0])

A  B   C
0   27  1   4
1   64  2  16
2  125  7  25

In [163]:
row = df.iloc[0, ::2]
row

A    3
C    2
Name: 0, dtype: int32

In [164]:
df - row

A   B    C
0  0.0 NaN  0.0
1  1.0 NaN  2.0
2  2.0 NaN  3.0

### 정렬(Sort)

In [166]:
s = pd.Series(range(5), index=['A', 'B', 'C',' D', 'E'])
s

A     0
B     1
C     2
 D    3
E     4
dtype: int64

In [167]:
s.sort_index()

 D    3
A     0
B     1
C     2
E     4
dtype: int64

In [168]:
s.sort_values()

A     0
B     1
C     2
 D    3
E     4
dtype: int64

In [169]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)),
                 index=[2, 4, 1, 3],
                 columns=list('BDAC'))
df

B  D  A  C
2  7  4  1  1
4  6  7  5  5
1  3  1  9  1
3  2  0  5  2

In [170]:
df.sort_index()

B  D  A  C
1  3  1  9  1
2  7  4  1  1
3  2  0  5  2
4  6  7  5  5

In [171]:
df.sort_index(axis=1)

A  B  C  D
2  1  7  1  4
4  5  6  5  7
1  9  3  1  1
3  5  2  2  0

In [172]:
df.sort_values(by='A')

B  D  A  C
2  7  4  1  1
4  6  7  5  5
3  2  0  5  2
1  3  1  9  1

In [173]:
df.sort_values(by=['A', 'C'])

B  D  A  C
2  7  4  1  1
3  2  0  5  2
4  6  7  5  5
1  3  1  9  1

### 순위(Ranking)


In [175]:
s = pd.Series([-2, 4, 7, 3, 0, 7, 5, -4, 2, 6])

In [176]:
s.rank()

0    2.0
1    6.0
2    9.5
3    5.0
4    3.0
5    9.5
6    7.0
7    1.0
8    4.0
9    8.0
dtype: float64

In [177]:
s.rank(method='first')

0     2.0
1     6.0
2     9.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [178]:
s.rank(method='max')

0     2.0
1     6.0
2    10.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

### 고성능 연산

In [179]:
nrow, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrow, ncols)) for i in range(4))

In [180]:
%timeit df1 + df2 + df3 + df4

104 ms ± 1.39 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [181]:
%timeit pd.eval('df1 + df2 + df3 + df4')

45.8 ms ± 1.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [182]:
%timeit df1* -df2 / (-df3 * df4)

169 ms ± 1.67 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [183]:
%timeit pd.eval('df1 * -df2 / (-df3 * df4)')

46.1 ms ± 1.72 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [184]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

62.8 ms ± 1.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [185]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

32 ms ± 1.78 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [186]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns=['A', 'B', 'C', 'D', 'E'])
df.head()

A         B         C         D         E
0  0.222230  0.778953  0.188016  0.960357  0.185821
1  0.832470  0.280229  0.386194  0.589328  0.398904
2  0.940785  0.278224  0.216691  0.055154  0.977815
3  0.458880  0.638957  0.751300  0.439420  0.288757
4  0.320697  0.003434  0.940397  0.295927  0.228923

In [187]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

18.9 ms ± 604 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [188]:
%timeit pd.eval('df.A + df.B / df.C - df.D * df.E')

6.3 ms ± 94 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [189]:
%timeit df.eval('A + B / C - D * E')

12.8 ms ± 77.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [190]:
df.eval('R = A + B / C - D * E', inplace=True)
df.head()

A         B         C         D         E         R
0  0.222230  0.778953  0.188016  0.960357  0.185821  4.186786
1  0.832470  0.280229  0.386194  0.589328  0.398904  1.323001
2  0.940785  0.278224  0.216691  0.055154  0.977815  2.170823
3  0.458880  0.638957  0.751300  0.439420  0.288757  1.182463
4  0.320697  0.003434  0.940397  0.295927  0.228923  0.256604

In [191]:
col_mean =df.mean(1)
df['A'] * col_mean

0         0.241570
1         0.528636
2         0.727461
3         0.287548
4         0.109357
            ...   
999995    0.432104
999996    0.163927
999997    0.409870
999998    0.434425
999999    0.759003
Length: 1000000, dtype: float64

In [192]:
df.eval('A + @col_mean')

0         1.309257
1         1.467491
2         1.714033
3         1.085510
4         0.661694
            ...   
999995    1.351963
999996    0.829361
999997    1.300386
999998    1.376798
999999    1.744469
Length: 1000000, dtype: float64

In [193]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]

A         B         C         D         E         R
4       0.320697  0.003434  0.940397  0.295927  0.228923  0.256604
11      0.042849  0.477105  0.788122  0.104484  0.759718  0.568841
12      0.064188  0.296234  0.718098  0.106845  0.586481  0.414050
16      0.272212  0.314151  0.816739  0.727579  0.296068  0.441439
24      0.353636  0.074217  0.875608  0.830990  0.677619 -0.124698
...          ...       ...       ...       ...       ...       ...
999974  0.234246  0.333034  0.659449  0.045328  0.013685  0.738644
999985  0.120968  0.132687  0.732792  0.916841  0.876359 -0.501443
999987  0.043356  0.078333  0.920646  0.611950  0.609161 -0.244335
999989  0.281945  0.413634  0.649327  0.275183  0.827683  0.691200
999996  0.325051  0.333427  0.653682  0.128653  0.860640  0.724403

[124829 rows x 6 columns]

In [194]:
pd.eval('df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]')

A         B         C         D         E         R
4       0.320697  0.003434  0.940397  0.295927  0.228923  0.256604
11      0.042849  0.477105  0.788122  0.104484  0.759718  0.568841
12      0.064188  0.296234  0.718098  0.106845  0.586481  0.414050
16      0.272212  0.314151  0.816739  0.727579  0.296068  0.441439
24      0.353636  0.074217  0.875608  0.830990  0.677619 -0.124698
...          ...       ...       ...       ...       ...       ...
999974  0.234246  0.333034  0.659449  0.045328  0.013685  0.738644
999985  0.120968  0.132687  0.732792  0.916841  0.876359 -0.501443
999987  0.043356  0.078333  0.920646  0.611950  0.609161 -0.244335
999989  0.281945  0.413634  0.649327  0.275183  0.827683  0.691200
999996  0.325051  0.333427  0.653682  0.128653  0.860640  0.724403

[124829 rows x 6 columns]

In [195]:
df.query('(A < 0.5) and (B < 0.5) and (C > 0.5)')

A         B         C         D         E         R
4       0.320697  0.003434  0.940397  0.295927  0.228923  0.256604
11      0.042849  0.477105  0.788122  0.104484  0.759718  0.568841
12      0.064188  0.296234  0.718098  0.106845  0.586481  0.414050
16      0.272212  0.314151  0.816739  0.727579  0.296068  0.441439
24      0.353636  0.074217  0.875608  0.830990  0.677619 -0.124698
...          ...       ...       ...       ...       ...       ...
999974  0.234246  0.333034  0.659449  0.045328  0.013685  0.738644
999985  0.120968  0.132687  0.732792  0.916841  0.876359 -0.501443
999987  0.043356  0.078333  0.920646  0.611950  0.609161 -0.244335
999989  0.281945  0.413634  0.649327  0.275183  0.827683  0.691200
999996  0.325051  0.333427  0.653682  0.128653  0.860640  0.724403

[124829 rows x 6 columns]

In [196]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

A         B         C         D         E         R
4       0.320697  0.003434  0.940397  0.295927  0.228923  0.256604
11      0.042849  0.477105  0.788122  0.104484  0.759718  0.568841
12      0.064188  0.296234  0.718098  0.106845  0.586481  0.414050
16      0.272212  0.314151  0.816739  0.727579  0.296068  0.441439
23      0.243355  0.396697  0.193370  0.112007  0.267082  2.264934
...          ...       ...       ...       ...       ...       ...
999982  0.065822  0.327617  0.144960  0.056471  0.471039  2.299265
999985  0.120968  0.132687  0.732792  0.916841  0.876359 -0.501443
999987  0.043356  0.078333  0.920646  0.611950  0.609161 -0.244335
999989  0.281945  0.413634  0.649327  0.275183  0.827683  0.691200
999996  0.325051  0.333427  0.653682  0.128653  0.860640  0.724403

[249158 rows x 6 columns]

In [197]:
df.query('A < @col_mean and B < @col_mean')

A         B         C         D         E         R
4       0.320697  0.003434  0.940397  0.295927  0.228923  0.256604
11      0.042849  0.477105  0.788122  0.104484  0.759718  0.568841
12      0.064188  0.296234  0.718098  0.106845  0.586481  0.414050
16      0.272212  0.314151  0.816739  0.727579  0.296068  0.441439
23      0.243355  0.396697  0.193370  0.112007  0.267082  2.264934
...          ...       ...       ...       ...       ...       ...
999982  0.065822  0.327617  0.144960  0.056471  0.471039  2.299265
999985  0.120968  0.132687  0.732792  0.916841  0.876359 -0.501443
999987  0.043356  0.078333  0.920646  0.611950  0.609161 -0.244335
999989  0.281945  0.413634  0.649327  0.275183  0.827683  0.691200
999996  0.325051  0.333427  0.653682  0.128653  0.860640  0.724403

[249158 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

In [199]:
s1 = pd.Series(['a', 'b'], index=[1, 2])
s2 = pd.Series(['c', 'd'], index=[3, 4])
pd.concat([s1, s2])

1    a
2    b
3    c
4    d
dtype: object

In [201]:
def create_df(cols, idx):
    data = {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
    return pd.DataFrame(data, idx)

In [203]:
df1 = create_df('AB', [1, 2])
df1

A   B
1  a1  b1
2  a2  b2

In [205]:
df2 = create_df('AB', [3, 4])
df2

A   B
3  a3  b3
4  a4  b4

In [206]:
pd.concat([df1, df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [208]:
df3 = create_df('AB', [0, 1])
df3

A   B
0  a0  b0
1  a1  b1

In [209]:
df4 = create_df('CD', [0, 1])
df4

C   D
0  c0  d0
1  c1  d1

In [210]:
pd.concat([df3, df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [211]:
pd.concat([df3, df4], axis=1)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [212]:
#pd.concat([df1, df3], verify_integrity=True)

In [213]:
pd.concat([df1, df3], ignore_index=True)

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [215]:
pd.concat([df1, df3], keys=['X', 'Y'])

A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [216]:
df5 = create_df('ABC', [1,2])
df6 = create_df('BCD', [3,4])
pd.concat([df5, df6])

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [217]:
pd.concat([df5, df6], join='inner')

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [218]:
df5.append(df6)

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

### 병합과 조인

In [219]:
df1 = pd.DataFrame({'학생' : ['홍길동', '이순신', '임꺽정', '김유신'],
                   '학과' : ['경영학과', '교육학과', '컴퓨터학과', '통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [221]:
df2 = pd.DataFrame({'학생' : ['홍길동', '이순신', '임꺽정', '김유신'],
                   '입학년도' : [2012, 2016, 2019, 2020]})
df2

학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [222]:
df3 = pd.merge(df1, df2)
df3

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [223]:
df4 = pd.DataFrame({'학과': ['경영학과', '교육학과', '컴퓨터학과', '통계학과'],
                   '학과정' : ['황희', '장영실', '안창호', '정약용']})
df4

학과  학과정
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [224]:
pd.merge(df3, df4)

학생     학과  입학년도  학과정
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [225]:
df5 = pd.DataFrame({'학과' : ['경영학과', '교육학과', '교육학과', '컴퓨터학과', '컴퓨터학과', '통계학과'],
                   '과목' : ['경영개론', '기초수학', '물리학', '프로그래밍', '운영체제', '확률론']})
df5

학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [227]:
pd.merge(df1, df5)

학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [228]:
pd.merge(df1, df2, on='학생')

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [229]:
df6 = pd.DataFrame({'이름' : ['홍길동', '이순신', '임꺽정', '김유신'],
                   '성적' : ['A', 'A+', 'B', 'A+']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

In [230]:
pd.merge(df1, df6, left_on='학생', right_on='이름')

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  A+

In [231]:
pd.merge(df1, df6, left_on='학생', right_on='이름').drop('이름', axis=1)

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  A+

In [232]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [233]:
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [234]:
mdf2

입학년도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [235]:
pd.merge(mdf1, mdf2, left_index=True, right_index=True)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [237]:
mdf1.join(df2)

학과   학생  입학년도
학생                   
홍길동   경영학과  NaN   NaN
이순신   교육학과  NaN   NaN
임꺽정  컴퓨터학과  NaN   NaN
김유신   통계학과  NaN   NaN

In [239]:
pd.merge(mdf1, df6, left_index=True, right_on='이름')

학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신  A+

In [240]:
df7 = pd.DataFrame({'이름':['홍길동', '이순신', '임꺽정'],
                   '주문음식' : ['햄버거', '피자', '짜장면']})
df7

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [241]:
df8 = pd.DataFrame({'이름' : ['홍길동', '이순신', '김유신'],
                   '주문음식' : ['콜라', '사이다', '커피']})
df8

이름 주문음식
0  홍길동   콜라
1  이순신  사이다
2  김유신   커피

In [242]:
pd.merge(df7, df8)

Empty DataFrame
Columns: [이름, 주문음식]
Index: []

In [243]:
pd.merge(df7, df8, how='inner')

Empty DataFrame
Columns: [이름, 주문음식]
Index: []

In [244]:
pd.merge(df7, df8, how='outer')

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면
3  홍길동   콜라
4  이순신  사이다
5  김유신   커피

In [245]:
pd.merge(df7, df8, how='left')

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [246]:
pd.merge(df7, df8, how='right')

이름 주문음식
0  홍길동   콜라
1  이순신  사이다
2  김유신   커피

In [247]:
df9 = pd.DataFrame({'이름' : ['홍길동', '이순신', '임꺽정', '김유신'],
                   '순위' : [3, 2, 4, 1]})
df9

이름  순위
0  홍길동   3
1  이순신   2
2  임꺽정   4
3  김유신   1

In [248]:
df10 = pd.DataFrame({'이름' : ['홍길동', '이순신', '임꺽정', '김유신'],
                    '순위' : [4, 1, 3, 2]})
df10

이름  순위
0  홍길동   4
1  이순신   1
2  임꺽정   3
3  김유신   2

In [249]:
pd.merge(df9, df10, on='이름')

이름  순위_x  순위_y
0  홍길동     3     4
1  이순신     2     1
2  임꺽정     4     3
3  김유신     1     2

In [250]:
pd.merge(df9, df10, on='이름', suffixes=['_인기', '_성적'])

이름  순위_인기  순위_성적
0  홍길동      3      4
1  이순신      2      1
2  임꺽정      4      3
3  김유신      1      2

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


In [251]:
df = pd.DataFrame([[1, 1.2, np.nan],
                  [2.4, 5.5, 4.2],
                  [np.nan, np.nan, np.nan],
                  [0.44, -3.1, -4.1]],
                 index=[1, 2, 3, 4],
                 columns=['A', 'B', 'C'])
df

A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [252]:
df.head(2)

A    B    C
1  1.0  1.2  NaN
2  2.4  5.5  4.2

In [253]:
df.tail(2)

A    B    C
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [254]:
df.describe()

A     B         C
count  3.000000  3.00  2.000000
mean   1.280000  1.20  0.050000
std    1.009554  4.30  5.868986
min    0.440000 -3.10 -4.100000
25%    0.720000 -0.95 -2.025000
50%    1.000000  1.20  0.050000
75%    1.700000  3.35  2.125000
max    2.400000  5.50  4.200000

In [255]:
print(df)
print(np.argmin(df), np.argmax(df))

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
2 2


In [256]:
print(df)
print(df.idxmin())
print(df.idxmax())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    4
B    4
C    4
dtype: int64
A    2
B    2
C    2
dtype: int64


In [258]:
print(df)
print(df.std())
print(df.var())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.009554
B    4.300000
C    5.868986
dtype: float64
A     1.0192
B    18.4900
C    34.4450
dtype: float64


In [259]:
print(df)
print(df.skew())
print(df.kurt())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.15207
B    0.00000
C        NaN
dtype: float64
A   NaN
B   NaN
C   NaN
dtype: float64


In [260]:
print(df)
print(df.sum())
print(df.cumsum())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    3.84
B    3.60
C    0.10
dtype: float64
      A    B    C
1  1.00  1.2  NaN
2  3.40  6.7  4.2
3   NaN  NaN  NaN
4  3.84  3.6  0.1


In [261]:
print(df)
print(df.prod())
print(df.cumprod())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A     1.056
B   -20.460
C   -17.220
dtype: float64
       A      B      C
1  1.000   1.20    NaN
2  2.400   6.60   4.20
3    NaN    NaN    NaN
4  1.056 -20.46 -17.22


In [262]:
df.diff()

A    B   C
1  NaN  NaN NaN
2  1.4  4.3 NaN
3  NaN  NaN NaN
4  NaN  NaN NaN

In [263]:
df.quantile()

A    1.00
B    1.20
C    0.05
Name: 0.5, dtype: float64

In [264]:
df.pct_change()

A         B        C
1       NaN       NaN      NaN
2  1.400000  3.583333      NaN
3  0.000000  0.000000  0.00000
4 -0.816667 -1.563636 -1.97619

In [265]:
df.corr()

A         B    C
A  1.000000  0.970725  1.0
B  0.970725  1.000000  1.0
C  1.000000  1.000000  1.0

In [266]:
df.corrwith(df.B)

A    0.970725
B    1.000000
C    1.000000
dtype: float64

In [267]:
df.cov()

A       B       C
A  1.0192   4.214   8.134
B  4.2140  18.490  35.690
C  8.1340  35.690  34.445

In [268]:
df['B'].unique()

array([ 1.2,  5.5,  nan, -3.1])

In [269]:
df['A'].value_counts()

2.40    1
0.44    1
1.00    1
Name: A, dtype: int64

### GroupBy 연산

In [3]:
df = pd.DataFrame({'c1' : ['a', 'a', 'b', 'b', 'c', 'd', 'b'],
                  'c2' : ['A', 'B', 'B', 'A', 'D', 'C', 'C'],
                  'c3' : np.random.randint(7),
                  'c4' : np.random.random(7)})
df

c1 c2  c3        c4
0  a  A   3  0.674265
1  a  B   3  0.207306
2  b  B   3  0.944438
3  b  A   3  0.490856
4  c  D   3  0.378876
5  d  C   3  0.655246
6  b  C   3  0.839020

In [4]:
df.dtypes

c1     object
c2     object
c3      int64
c4    float64
dtype: object

In [5]:
df['c3'].groupby(df['c1']).mean()

c1
a    3
b    3
c    3
d    3
Name: c3, dtype: int64

In [6]:
df['c4'].groupby(df['c2']).std()

c2
A    0.129690
B    0.521230
C    0.129947
D         NaN
Name: c4, dtype: float64

In [8]:
df['c4'].groupby([df['c1'], df['c2']]).mean()

c1  c2
a   A     0.674265
    B     0.207306
b   A     0.490856
    B     0.944438
    C     0.839020
c   D     0.378876
d   C     0.655246
Name: c4, dtype: float64

In [9]:
df['c4'].groupby([df['c1'], df['c2']]).mean().unstack()

c2         A         B         C         D
c1                                        
a   0.674265  0.207306       NaN       NaN
b   0.490856  0.944438  0.839020       NaN
c        NaN       NaN       NaN  0.378876
d        NaN       NaN  0.655246       NaN

In [10]:
df.groupby('c1').mean()

c3        c4
c1              
a    3  0.440786
b    3  0.758104
c    3  0.378876
d    3  0.655246

In [11]:
df.groupby(['c1', 'c2']).mean()

c3        c4
c1 c2              
a  A    3  0.674265
   B    3  0.207306
b  A    3  0.490856
   B    3  0.944438
   C    3  0.839020
c  D    3  0.378876
d  C    3  0.655246

In [12]:
df.groupby(['c1', 'c2']).size()

c1  c2
a   A     1
    B     1
b   A     1
    B     1
    C     1
c   D     1
d   C     1
dtype: int64

In [13]:
for c1, group in df.groupby('c1'):
    print(c1)
    print(group)

a
  c1 c2  c3        c4
0  a  A   3  0.674265
1  a  B   3  0.207306
b
  c1 c2  c3        c4
2  b  B   3  0.944438
3  b  A   3  0.490856
6  b  C   3  0.839020
c
  c1 c2  c3        c4
4  c  D   3  0.378876
d
  c1 c2  c3        c4
5  d  C   3  0.655246


In [14]:
for (c1, c2), group in df.groupby(['c1', 'c2']):
    print((c1, c2))
    print(group)

('a', 'A')
  c1 c2  c3        c4
0  a  A   3  0.674265
('a', 'B')
  c1 c2  c3        c4
1  a  B   3  0.207306
('b', 'A')
  c1 c2  c3        c4
3  b  A   3  0.490856
('b', 'B')
  c1 c2  c3        c4
2  b  B   3  0.944438
('b', 'C')
  c1 c2  c3       c4
6  b  C   3  0.83902
('c', 'D')
  c1 c2  c3        c4
4  c  D   3  0.378876
('d', 'C')
  c1 c2  c3        c4
5  d  C   3  0.655246


In [16]:
df.groupby(['c1', 'c2'])[['c4']].mean()

c4
c1 c2          
a  A   0.674265
   B   0.207306
b  A   0.490856
   B   0.944438
   C   0.839020
c  D   0.378876
d  C   0.655246

In [18]:
df.groupby('c1')['c3'].quantile()

c1
a    3.0
b    3.0
c    3.0
d    3.0
Name: c3, dtype: float64

In [19]:
df.groupby('c1')['c3'].median()

c1
a    3
b    3
c    3
d    3
Name: c3, dtype: int64

In [20]:
df.groupby('c1')['c3'].std()

c1
a    0.0
b    0.0
c    NaN
d    NaN
Name: c3, dtype: float64

In [22]:
df.groupby(['c1', 'c2'])['c4'].agg(['mean', 'min', 'max'])

mean       min       max
c1 c2                              
a  A   0.674265  0.674265  0.674265
   B   0.207306  0.207306  0.207306
b  A   0.490856  0.490856  0.490856
   B   0.944438  0.944438  0.944438
   C   0.839020  0.839020  0.839020
c  D   0.378876  0.378876  0.378876
d  C   0.655246  0.655246  0.655246

In [23]:
df.groupby(['c1', 'c2'], as_index=False)['c4'].mean() 

c1 c2        c4
0  a  A  0.674265
1  a  B  0.207306
2  b  A  0.490856
3  b  B  0.944438
4  b  C  0.839020
5  c  D  0.378876
6  d  C  0.655246

In [24]:
df.groupby(['c1', 'c2'], group_keys=False)['c4'].mean()

c1  c2
a   A     0.674265
    B     0.207306
b   A     0.490856
    B     0.944438
    C     0.839020
c   D     0.378876
d   C     0.655246
Name: c4, dtype: float64

In [27]:
def top(df, n=3, column='c1'):
    return df.sort_values(by=column)[-n:]

top(df, n=5)

c1 c2  c3        c4
2  b  B   3  0.944438
3  b  A   3  0.490856
6  b  C   3  0.839020
4  c  D   3  0.378876
5  d  C   3  0.655246

In [28]:
df.groupby('c1').apply(top)

c1 c2  c3        c4
c1                      
a  0  a  A   3  0.674265
   1  a  B   3  0.207306
b  2  b  B   3  0.944438
   3  b  A   3  0.490856
   6  b  C   3  0.839020
c  4  c  D   3  0.378876
d  5  d  C   3  0.655246

### 피벗 테이블(Pivot Table)


In [29]:
df.pivot_table(['c3', 'c4'],
              index=['c1'],
              columns=['c2'])

c3                       c4                              
c2    A    B    C    D         A         B         C         D
c1                                                            
a   3.0  3.0  NaN  NaN  0.674265  0.207306       NaN       NaN
b   3.0  3.0  3.0  NaN  0.490856  0.944438  0.839020       NaN
c   NaN  NaN  NaN  3.0       NaN       NaN       NaN  0.378876
d   NaN  NaN  3.0  NaN       NaN       NaN  0.655246       NaN

In [30]:
df.pivot_table(['c3', 'c4'],
              index=['c1'],
              columns=['c2'],
              margins=True)

c3                           c4                                        
c2     A    B    C    D All         A         B         C         D       All
c1                                                                           
a    3.0  3.0  NaN  NaN   3  0.674265  0.207306       NaN       NaN  0.440786
b    3.0  3.0  3.0  NaN   3  0.490856  0.944438  0.839020       NaN  0.758104
c    NaN  NaN  NaN  3.0   3       NaN       NaN       NaN  0.378876  0.378876
d    NaN  NaN  3.0  NaN   3       NaN       NaN  0.655246       NaN  0.655246
All  3.0  3.0  3.0  3.0   3  0.582561  0.575872  0.747133  0.378876  0.598572

In [31]:
df.pivot_table(['c3', 'c4'],
              index=['c1'],
              columns=['c2'],
              margins=True,
              aggfunc=sum)

c3                           c4                                        
c2     A    B    C    D All         A         B         C         D       All
c1                                                                           
a    3.0  3.0  NaN  NaN   6  0.674265  0.207306       NaN       NaN  0.881572
b    3.0  3.0  3.0  NaN   9  0.490856  0.944438  0.839020       NaN  2.274313
c    NaN  NaN  NaN  3.0   3       NaN       NaN       NaN  0.378876  0.378876
d    NaN  NaN  3.0  NaN   3       NaN       NaN  0.655246       NaN  0.655246
All  6.0  6.0  6.0  3.0  21  1.165121  1.151744  1.494266  0.378876  4.190007

In [32]:
df.pivot_table(['c3', 'c4'],
              index=['c1'],
              columns=['c2'],
              margins=True,
              aggfunc=sum,
              fill_value=0)

c3                     c4                                        
c2   A  B  C  D All         A         B         C         D       All
c1                                                                   
a    3  3  0  0   6  0.674265  0.207306  0.000000  0.000000  0.881572
b    3  3  3  0   9  0.490856  0.944438  0.839020  0.000000  2.274313
c    0  0  0  3   3  0.000000  0.000000  0.000000  0.378876  0.378876
d    0  0  3  0   3  0.000000  0.000000  0.655246  0.000000  0.655246
All  6  6  6  3  21  1.165121  1.151744  1.494266  0.378876  4.190007

In [33]:
pd.crosstab(df.c1, df.c2)

c2  A  B  C  D
c1            
a   1  1  0  0
b   1  1  1  0
c   0  0  0  1
d   0  0  1  0

In [34]:
pd.crosstab(df.c1, df.c2, values=df.c3, aggfunc=sum, margins=True)

c2     A    B    C    D  All
c1                          
a    3.0  3.0  NaN  NaN    6
b    3.0  3.0  3.0  NaN    9
c    NaN  NaN  NaN  3.0    3
d    NaN  NaN  3.0  NaN    3
All  6.0  6.0  6.0  3.0   21

### 범주형(Categorical) 데이터


In [35]:
s = pd.Series(['c1', 'c2', 'c1', 'c2', 'c1'] * 2)
s

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
dtype: object

In [36]:
pd.unique(s)

array(['c1', 'c2'], dtype=object)

In [37]:
pd.value_counts(s)

c1    6
c2    4
dtype: int64

In [38]:
code = pd.Series([0, 1, 0, 1, 0] * 2)
code

0    0
1    1
2    0
3    1
4    0
5    0
6    1
7    0
8    1
9    0
dtype: int64

In [39]:
d = pd.Series(['c1', 'c2'])
d

0    c1
1    c2
dtype: object

In [40]:
d.take(code)

0    c1
1    c2
0    c1
1    c2
0    c1
0    c1
1    c2
0    c1
1    c2
0    c1
dtype: object

In [41]:
df = pd.DataFrame({'id': np.arange(len(s)),
                  'c':s,
                  'v':np.random.randint(1000, 5000, size=len(s))})
df

id   c     v
0   0  c1  2087
1   1  c2  2042
2   2  c1  3759
3   3  c2  4916
4   4  c1  1140
5   5  c1  1481
6   6  c2  4534
7   7  c1  2069
8   8  c2  4835
9   9  c1  2126

In [43]:
c = df['c'].astype('category')
c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [44]:
c.values

['c1', 'c2', 'c1', 'c2', 'c1', 'c1', 'c2', 'c1', 'c2', 'c1']
Categories (2, object): ['c1', 'c2']

In [45]:
c.values.categories

Index(['c1', 'c2'], dtype='object')

In [46]:
c.values.codes

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int8)

In [47]:
df['c'] = c
df.c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [48]:
c = pd.Categorical(['c1', 'c2', 'c3', 'c1', 'c2'])
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [49]:
categories = ['c1', 'c2', 'c3']
codes = [0, 1, 2, 0, 1]
c = pd.Categorical.from_codes(codes, categories)
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [50]:
pd.Categorical.from_codes(code, categories, ordered=True)

['c1', 'c2', 'c1', 'c2', 'c1', 'c1', 'c2', 'c1', 'c2', 'c1']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [51]:
c.as_ordered()

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [52]:
c.codes

array([0, 1, 2, 0, 1], dtype=int8)

In [53]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')

In [54]:
c = c.set_categories(['c1', 'c2', 'c3', 'c4', 'c5'])
c.categories

Index(['c1', 'c2', 'c3', 'c4', 'c5'], dtype='object')

In [55]:
c.value_counts()

c1    2
c2    2
c3    1
c4    0
c5    0
dtype: int64

In [56]:
c[c.isin(['c1', 'c3'])]

['c1', 'c3', 'c1']
Categories (5, object): ['c1', 'c2', 'c3', 'c4', 'c5']

In [57]:
c = c.remove_unused_categories()

In [58]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')

## 문자열 연산

#### 문자열 연산자

In [59]:
name_tuple = ['Suan Lee', 'Steven Jobs', 'Larry page', 'Elon Musk', None, 'Bill Gates', 'Mark Zuckerberg', 'Jeff Bezos']
names = pd.Series(name_tuple)
names

0           Suan Lee
1        Steven Jobs
2         Larry page
3          Elon Musk
4               None
5         Bill Gates
6    Mark Zuckerberg
7         Jeff Bezos
dtype: object

In [60]:
names.str.lower()

0           suan lee
1        steven jobs
2         larry page
3          elon musk
4               None
5         bill gates
6    mark zuckerberg
7         jeff bezos
dtype: object

In [61]:
names.str.len()

0     8.0
1    11.0
2    10.0
3     9.0
4     NaN
5    10.0
6    15.0
7    10.0
dtype: float64

In [62]:
names.str.split()

0           [Suan, Lee]
1        [Steven, Jobs]
2         [Larry, page]
3          [Elon, Musk]
4                  None
5         [Bill, Gates]
6    [Mark, Zuckerberg]
7         [Jeff, Bezos]
dtype: object

#### 기타 연산자


In [63]:
names.str[0:4]

0    Suan
1    Stev
2    Larr
3    Elon
4    None
5    Bill
6    Mark
7    Jeff
dtype: object

In [64]:
names.str.split().str.get(-1)

0           Lee
1          Jobs
2          page
3          Musk
4          None
5         Gates
6    Zuckerberg
7         Bezos
dtype: object

In [65]:
names.str.repeat(2)

0                  Suan LeeSuan Lee
1            Steven JobsSteven Jobs
2              Larry pageLarry page
3                Elon MuskElon Musk
4                              None
5              Bill GatesBill Gates
6    Mark ZuckerbergMark Zuckerberg
7              Jeff BezosJeff Bezos
dtype: object

In [66]:
names.str.join('*')

0                  S*u*a*n* *L*e*e
1            S*t*e*v*e*n* *J*o*b*s
2              L*a*r*r*y* *p*a*g*e
3                E*l*o*n* *M*u*s*k
4                             None
5              B*i*l*l* *G*a*t*e*s
6    M*a*r*k* *Z*u*c*k*e*r*b*e*r*g
7              J*e*f*f* *B*e*z*o*s
dtype: object

#### 정규표현식


In [67]:
names.str.match('([A-Za-z]+)')

0    True
1    True
2    True
3    True
4    None
5    True
6    True
7    True
dtype: object

In [68]:
names.str.findall('([A-Za-z]+)')

0           [Suan, Lee]
1        [Steven, Jobs]
2         [Larry, page]
3          [Elon, Musk]
4                  None
5         [Bill, Gates]
6    [Mark, Zuckerberg]
7         [Jeff, Bezos]
dtype: object

## 시계열 처리

In [69]:
idx = pd.DatetimeIndex(['2019-01-01', '2020-01-01', '2020-02-01',
                       '2020-02-02', '2020-03-01'])
s = pd.Series([0, 1, 2, 3, 4], index =idx)
s

2019-01-01    0
2020-01-01    1
2020-02-01    2
2020-02-02    3
2020-03-01    4
dtype: int64

In [70]:
s['2020-01-01':]

2020-01-01    1
2020-02-01    2
2020-02-02    3
2020-03-01    4
dtype: int64

In [71]:
s[:'2020-01-01']

2019-01-01    0
2020-01-01    1
dtype: int64

In [72]:
s['2019']

2019-01-01    0
dtype: int64

#### 시계열 데이터 구조


In [73]:
from datetime import datetime
dates = pd.to_datetime(['12-12-2019', datetime(2020, 1, 1), '2nd of Feb, 2020', '2020-Mar-4', '20200701'])
dates

DatetimeIndex(['2019-12-12', '2020-01-01', '2020-02-02', '2020-03-04',
               '2020-07-01'],
              dtype='datetime64[ns]', freq=None)

In [74]:
dates.to_period('D')

PeriodIndex(['2019-12-12', '2020-01-01', '2020-02-02', '2020-03-04',
             '2020-07-01'],
            dtype='period[D]', freq='D')

In [75]:
dates - dates[0]

TimedeltaIndex(['0 days', '20 days', '52 days', '83 days', '202 days'], dtype='timedelta64[ns]', freq=None)

In [76]:
pd.date_range('2020-01-01', '2020-07-01')

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-06-22', '2020-06-23', '2020-06-24', '2020-06-25',
               '2020-06-26', '2020-06-27', '2020-06-28', '2020-06-29',
               '2020-06-30', '2020-07-01'],
              dtype='datetime64[ns]', length=183, freq='D')

In [77]:
pd.date_range('2020-01-01', periods=7)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07'],
              dtype='datetime64[ns]', freq='D')

In [78]:
pd.date_range('2020-01-01', periods=7, freq='M')

DatetimeIndex(['2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30',
               '2020-05-31', '2020-06-30', '2020-07-31'],
              dtype='datetime64[ns]', freq='M')

In [79]:
pd.date_range('2020-01-01', periods=7, freq='H')

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 01:00:00',
               '2020-01-01 02:00:00', '2020-01-01 03:00:00',
               '2020-01-01 04:00:00', '2020-01-01 05:00:00',
               '2020-01-01 06:00:00'],
              dtype='datetime64[ns]', freq='H')

In [80]:
idx = pd.to_datetime(['2020-01-01 12:00:00', '2020-01-02 00:00:00'] + [None])
idx

DatetimeIndex(['2020-01-01 12:00:00', '2020-01-02 00:00:00', 'NaT'], dtype='datetime64[ns]', freq=None)

In [81]:
idx[2]

NaT

In [82]:
pd.isnull(idx)

array([False, False,  True])

### 시계열 기본

In [83]:
dates= [datetime(2020, 1, 1), datetime(2020, 1, 2), datetime(2020, 1, 4), datetime(2020, 1, 7),
       datetime(2020, 1, 10), datetime(2020, 1, 11), datetime(2020, 1, 15)]
dates

[datetime.datetime(2020, 1, 1, 0, 0),
 datetime.datetime(2020, 1, 2, 0, 0),
 datetime.datetime(2020, 1, 4, 0, 0),
 datetime.datetime(2020, 1, 7, 0, 0),
 datetime.datetime(2020, 1, 10, 0, 0),
 datetime.datetime(2020, 1, 11, 0, 0),
 datetime.datetime(2020, 1, 15, 0, 0)]

In [84]:
ts = pd.Series(np.random.randn(7), index=dates)
ts

2020-01-01    0.263991
2020-01-02    0.741761
2020-01-04    0.969564
2020-01-07    1.164782
2020-01-10    0.838253
2020-01-11   -0.039622
2020-01-15   -0.073338
dtype: float64

In [85]:
ts.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-04', '2020-01-07',
               '2020-01-10', '2020-01-11', '2020-01-15'],
              dtype='datetime64[ns]', freq=None)

In [86]:
ts.index[0]

Timestamp('2020-01-01 00:00:00')

In [87]:
ts[ts.index[2]]

0.9695642271317747

In [88]:
ts['20200104']

0.9695642271317747

In [89]:
ts['1/4/2020']

0.9695642271317747

In [90]:
ts = pd.Series(np.random.randn(1000),
              index=pd.date_range('2017-10-01', periods=1000))
ts

2017-10-01   -0.960662
2017-10-02   -1.792537
2017-10-03    0.132584
2017-10-04   -0.677342
2017-10-05   -0.911321
                ...   
2020-06-22   -0.140769
2020-06-23    1.144656
2020-06-24    1.631823
2020-06-25    0.185229
2020-06-26   -1.401777
Freq: D, Length: 1000, dtype: float64

In [91]:
ts['2020']

2020-01-01   -0.451343
2020-01-02    0.544365
2020-01-03    0.446798
2020-01-04    0.416157
2020-01-05    1.172374
                ...   
2020-06-22   -0.140769
2020-06-23    1.144656
2020-06-24    1.631823
2020-06-25    0.185229
2020-06-26   -1.401777
Freq: D, Length: 178, dtype: float64

In [92]:
ts['2020-06']

2020-06-01    0.842111
2020-06-02    0.198303
2020-06-03    0.656753
2020-06-04   -1.408915
2020-06-05    0.137344
2020-06-06    0.412319
2020-06-07    0.563326
2020-06-08   -0.472421
2020-06-09   -0.467774
2020-06-10   -0.905605
2020-06-11   -2.658735
2020-06-12    0.053256
2020-06-13   -0.287946
2020-06-14    0.938112
2020-06-15   -0.211522
2020-06-16   -0.879909
2020-06-17    1.580337
2020-06-18    0.241675
2020-06-19    1.044349
2020-06-20   -0.239184
2020-06-21   -0.778864
2020-06-22   -0.140769
2020-06-23    1.144656
2020-06-24    1.631823
2020-06-25    0.185229
2020-06-26   -1.401777
Freq: D, dtype: float64

In [93]:
ts[datetime(2020, 6, 20):]

2020-06-20   -0.239184
2020-06-21   -0.778864
2020-06-22   -0.140769
2020-06-23    1.144656
2020-06-24    1.631823
2020-06-25    0.185229
2020-06-26   -1.401777
Freq: D, dtype: float64

In [94]:
ts['2020-06-10':'2020-06-20']

2020-06-10   -0.905605
2020-06-11   -2.658735
2020-06-12    0.053256
2020-06-13   -0.287946
2020-06-14    0.938112
2020-06-15   -0.211522
2020-06-16   -0.879909
2020-06-17    1.580337
2020-06-18    0.241675
2020-06-19    1.044349
2020-06-20   -0.239184
Freq: D, dtype: float64

In [95]:
tdf = pd.DataFrame(np.random.randn(1000, 4),
                  index=pd.date_range('2017-10-01', periods=1000),
                  columns=['A', 'B', 'C', 'D'])
tdf

A         B         C         D
2017-10-01 -0.645465  1.475549 -0.127287  0.706699
2017-10-02  1.545780  0.131715  0.627648 -0.834889
2017-10-03 -0.771348  0.721854 -0.902990 -2.715995
2017-10-04  0.356215  1.361846 -0.800140  1.218291
2017-10-05 -1.524915 -1.346660  0.672298  0.754435
...              ...       ...       ...       ...
2020-06-22 -0.715286 -0.473431 -0.279020  0.100177
2020-06-23  1.720231  1.733301  0.190702 -1.223960
2020-06-24  1.260663  1.022764 -1.111716 -0.021434
2020-06-25 -1.268088  0.151027  0.471630  0.917494
2020-06-26  1.154403  1.130113 -0.271328 -0.278995

[1000 rows x 4 columns]

In [96]:
tdf['2020']

<ipython-input-96-8f66df2f472c>:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  tdf['2020']


A         B         C         D
2020-01-01  1.146488 -1.807088  0.202516  0.346479
2020-01-02 -0.818374  0.442638 -0.496340 -0.197460
2020-01-03  0.221955  1.051605  0.127932 -0.444380
2020-01-04  0.430497 -0.668448 -0.644132  0.120934
2020-01-05 -0.144829  0.804610  0.684053  1.556291
...              ...       ...       ...       ...
2020-06-22 -0.715286 -0.473431 -0.279020  0.100177
2020-06-23  1.720231  1.733301  0.190702 -1.223960
2020-06-24  1.260663  1.022764 -1.111716 -0.021434
2020-06-25 -1.268088  0.151027  0.471630  0.917494
2020-06-26  1.154403  1.130113 -0.271328 -0.278995

[178 rows x 4 columns]

In [97]:
tdf.loc['2020-06']

A         B         C         D
2020-06-01  0.434211  1.053955  1.228545  0.094094
2020-06-02  1.548504  0.696717  0.276815 -0.437064
2020-06-03 -1.174143  0.203954  1.633648 -0.934881
2020-06-04 -0.227723  0.206088  0.006199  1.377339
2020-06-05  0.819965  0.305830  1.017664 -0.328019
2020-06-06 -0.468377  1.651363 -0.169807  0.933420
2020-06-07 -0.103158  0.130499  1.217279 -1.778587
2020-06-08  0.047540  1.023474  0.392994 -1.761869
2020-06-09  0.201195 -1.456836 -0.408648  0.471249
2020-06-10  1.356710 -2.172230  1.553144  0.285334
2020-06-11 -1.221596  0.090355  1.887684 -0.594212
2020-06-12  0.601817  0.889545 -1.431301 -0.733255
2020-06-13 -0.902523  0.874048 -2.070890 -1.562480
2020-06-14  0.951827  0.754432 -0.305397 -0.102046
2020-06-15 -1.148971  0.752140 -0.068756  0.483591
2020-06-16  1.735287  0.868374 -0.093591 -0.169226
2020-06-17 -1.246150  1.895251  0.525565  0.842796
2020-06-18  1.175326 -1.758939  0.758057  0.580363
2020-06-19 -0.747186  0.926587  1.445428  1.221069
2020-06-20  0.463491 -1.133415 -1.399947 -0.770776
2020-06-21  1.190164  0.612301  0.844391  0.112101
2020-06-22 -0.715286 -0.473431 -0.279020  0.100177
2020-06-23  1.720231  1.733301  0.190702 -1.223960
2020-06-24  1.260663  1.022764 -1.111716 -0.021434
2020-06-25 -1.268088  0.151027  0.471630  0.917494
2020-06-26  1.154403  1.130113 -0.271328 -0.278995

In [98]:
tdf['2020-06-20':]

A         B         C         D
2020-06-20  0.463491 -1.133415 -1.399947 -0.770776
2020-06-21  1.190164  0.612301  0.844391  0.112101
2020-06-22 -0.715286 -0.473431 -0.279020  0.100177
2020-06-23  1.720231  1.733301  0.190702 -1.223960
2020-06-24  1.260663  1.022764 -1.111716 -0.021434
2020-06-25 -1.268088  0.151027  0.471630  0.917494
2020-06-26  1.154403  1.130113 -0.271328 -0.278995

In [99]:
tdf['C']

2017-10-01   -0.127287
2017-10-02    0.627648
2017-10-03   -0.902990
2017-10-04   -0.800140
2017-10-05    0.672298
                ...   
2020-06-22   -0.279020
2020-06-23    0.190702
2020-06-24   -1.111716
2020-06-25    0.471630
2020-06-26   -0.271328
Freq: D, Name: C, Length: 1000, dtype: float64

In [100]:
tdf['C']

2017-10-01   -0.127287
2017-10-02    0.627648
2017-10-03   -0.902990
2017-10-04   -0.800140
2017-10-05    0.672298
                ...   
2020-06-22   -0.279020
2020-06-23    0.190702
2020-06-24   -1.111716
2020-06-25    0.471630
2020-06-26   -0.271328
Freq: D, Name: C, Length: 1000, dtype: float64

In [102]:
ts = pd.Series(np.random.randn(10),
              index=pd.DatetimeIndex(['2020-01-01', '2020-01-01', '2020-01-02', '2020-01-02', '2020-01-03',
                                     '2020-01-04', '2020-01-05', '2020-01-05', '2020-01-06', '2020-01-07']))
ts

2020-01-01    0.141050
2020-01-01    0.538580
2020-01-02   -0.855798
2020-01-02    0.824855
2020-01-03   -1.075796
2020-01-04   -1.415578
2020-01-05    0.782463
2020-01-05   -0.903427
2020-01-06    1.283459
2020-01-07   -0.911562
dtype: float64

In [103]:
ts.index.is_unique

False

In [104]:
ts['2020-01-01']

2020-01-01    0.14105
2020-01-01    0.53858
dtype: float64

In [105]:
ts.groupby(level=0).mean()

2020-01-01    0.339815
2020-01-02   -0.015471
2020-01-03   -1.075796
2020-01-04   -1.415578
2020-01-05   -0.060482
2020-01-06    1.283459
2020-01-07   -0.911562
dtype: float64

In [106]:
pd.date_range('2020-01-01', '2020-07-01')

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-06-22', '2020-06-23', '2020-06-24', '2020-06-25',
               '2020-06-26', '2020-06-27', '2020-06-28', '2020-06-29',
               '2020-06-30', '2020-07-01'],
              dtype='datetime64[ns]', length=183, freq='D')

In [111]:
pd.date_range(start='2020-01-01', periods=10)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [113]:
pd.date_range(end='2020-07-01', periods=10)

DatetimeIndex(['2020-06-22', '2020-06-23', '2020-06-24', '2020-06-25',
               '2020-06-26', '2020-06-27', '2020-06-28', '2020-06-29',
               '2020-06-30', '2020-07-01'],
              dtype='datetime64[ns]', freq='D')

In [108]:
pd.date_range('2020-01-01', '2020-07-01', freq='B')

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-06',
               '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
               '2020-01-13', '2020-01-14',
               ...
               '2020-06-18', '2020-06-19', '2020-06-22', '2020-06-23',
               '2020-06-24', '2020-06-25', '2020-06-26', '2020-06-29',
               '2020-06-30', '2020-07-01'],
              dtype='datetime64[ns]', length=131, freq='B')

### 주기와 오프셋


In [114]:
pd.timedelta_range(0, periods=12, freq='H')

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00', '0 days 05:00:00',
                '0 days 06:00:00', '0 days 07:00:00', '0 days 08:00:00',
                '0 days 09:00:00', '0 days 10:00:00', '0 days 11:00:00'],
               dtype='timedelta64[ns]', freq='H')

In [115]:
pd.timedelta_range(0, periods=60, freq='T')

TimedeltaIndex(['0 days 00:00:00', '0 days 00:01:00', '0 days 00:02:00',
                '0 days 00:03:00', '0 days 00:04:00', '0 days 00:05:00',
                '0 days 00:06:00', '0 days 00:07:00', '0 days 00:08:00',
                '0 days 00:09:00', '0 days 00:10:00', '0 days 00:11:00',
                '0 days 00:12:00', '0 days 00:13:00', '0 days 00:14:00',
                '0 days 00:15:00', '0 days 00:16:00', '0 days 00:17:00',
                '0 days 00:18:00', '0 days 00:19:00', '0 days 00:20:00',
                '0 days 00:21:00', '0 days 00:22:00', '0 days 00:23:00',
                '0 days 00:24:00', '0 days 00:25:00', '0 days 00:26:00',
                '0 days 00:27:00', '0 days 00:28:00', '0 days 00:29:00',
                '0 days 00:30:00', '0 days 00:31:00', '0 days 00:32:00',
                '0 days 00:33:00', '0 days 00:34:00', '0 days 00:35:00',
                '0 days 00:36:00', '0 days 00:37:00', '0 days 00:38:00',
                '0 days 00:39:00', '0 days 00:40:00

In [116]:
pd.timedelta_range(0, periods=10, freq='1H30T')

TimedeltaIndex(['0 days 00:00:00', '0 days 01:30:00', '0 days 03:00:00',
                '0 days 04:30:00', '0 days 06:00:00', '0 days 07:30:00',
                '0 days 09:00:00', '0 days 10:30:00', '0 days 12:00:00',
                '0 days 13:30:00'],
               dtype='timedelta64[ns]', freq='90T')

In [119]:
pd.date_range('2020-01-01', periods=20, freq='B')

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-06',
               '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10',
               '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
               '2020-01-17', '2020-01-20', '2020-01-21', '2020-01-22',
               '2020-01-23', '2020-01-24', '2020-01-27', '2020-01-28'],
              dtype='datetime64[ns]', freq='B')

In [120]:
pd.date_range('2020-01-01', periods=30, freq='2H')

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 02:00:00',
               '2020-01-01 04:00:00', '2020-01-01 06:00:00',
               '2020-01-01 08:00:00', '2020-01-01 10:00:00',
               '2020-01-01 12:00:00', '2020-01-01 14:00:00',
               '2020-01-01 16:00:00', '2020-01-01 18:00:00',
               '2020-01-01 20:00:00', '2020-01-01 22:00:00',
               '2020-01-02 00:00:00', '2020-01-02 02:00:00',
               '2020-01-02 04:00:00', '2020-01-02 06:00:00',
               '2020-01-02 08:00:00', '2020-01-02 10:00:00',
               '2020-01-02 12:00:00', '2020-01-02 14:00:00',
               '2020-01-02 16:00:00', '2020-01-02 18:00:00',
               '2020-01-02 20:00:00', '2020-01-02 22:00:00',
               '2020-01-03 00:00:00', '2020-01-03 02:00:00',
               '2020-01-03 04:00:00', '2020-01-03 06:00:00',
               '2020-01-03 08:00:00', '2020-01-03 10:00:00'],
              dtype='datetime64[ns]', freq='2H')

In [121]:
pd.date_range('2020-01-01', periods=20, freq='S')

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 00:00:01',
               '2020-01-01 00:00:02', '2020-01-01 00:00:03',
               '2020-01-01 00:00:04', '2020-01-01 00:00:05',
               '2020-01-01 00:00:06', '2020-01-01 00:00:07',
               '2020-01-01 00:00:08', '2020-01-01 00:00:09',
               '2020-01-01 00:00:10', '2020-01-01 00:00:11',
               '2020-01-01 00:00:12', '2020-01-01 00:00:13',
               '2020-01-01 00:00:14', '2020-01-01 00:00:15',
               '2020-01-01 00:00:16', '2020-01-01 00:00:17',
               '2020-01-01 00:00:18', '2020-01-01 00:00:19'],
              dtype='datetime64[ns]', freq='S')

### 시프트(Shift)

In [122]:
ts = pd.Series(np.random.randn(5),
              index=pd.date_range('2020-01-01', periods=5, freq='B'))
ts

2020-01-01    0.493169
2020-01-02   -0.088100
2020-01-03    1.945302
2020-01-06   -1.836782
2020-01-07   -0.467373
Freq: B, dtype: float64

In [123]:
ts.shift(1)

2020-01-01         NaN
2020-01-02    0.493169
2020-01-03   -0.088100
2020-01-06    1.945302
2020-01-07   -1.836782
Freq: B, dtype: float64

In [124]:
ts.shift(3)

2020-01-01         NaN
2020-01-02         NaN
2020-01-03         NaN
2020-01-06    0.493169
2020-01-07   -0.088100
Freq: B, dtype: float64

In [125]:
ts.shift(-2)

2020-01-01    1.945302
2020-01-02   -1.836782
2020-01-03   -0.467373
2020-01-06         NaN
2020-01-07         NaN
Freq: B, dtype: float64

In [126]:
ts.shift(3, freq='B')

2020-01-06    0.493169
2020-01-07   -0.088100
2020-01-08    1.945302
2020-01-09   -1.836782
2020-01-10   -0.467373
Freq: B, dtype: float64

In [127]:
ts.shift(2, freq='W')

2020-01-12    0.493169
2020-01-12   -0.088100
2020-01-12    1.945302
2020-01-19   -1.836782
2020-01-19   -0.467373
dtype: float64

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

In [128]:
import pytz
pytz.common_timezones

['Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers', 'Africa/Asmara', 'Africa/Bamako', 'Africa/Bangui', 'Africa/Banjul', 'Africa/Bissau', 'Africa/Blantyre', 'Africa/Brazzaville', 'Africa/Bujumbura', 'Africa/Cairo', 'Africa/Casablanca', 'Africa/Ceuta', 'Africa/Conakry', 'Africa/Dakar', 'Africa/Dar_es_Salaam', 'Africa/Djibouti', 'Africa/Douala', 'Africa/El_Aaiun', 'Africa/Freetown', 'Africa/Gaborone', 'Africa/Harare', 'Africa/Johannesburg', 'Africa/Juba', 'Africa/Kampala', 'Africa/Khartoum', 'Africa/Kigali', 'Africa/Kinshasa', 'Africa/Lagos', 'Africa/Libreville', 'Africa/Lome', 'Africa/Luanda', 'Africa/Lubumbashi', 'Africa/Lusaka', 'Africa/Malabo', 'Africa/Maputo', 'Africa/Maseru', 'Africa/Mbabane', 'Africa/Mogadishu', 'Africa/Monrovia', 'Africa/Nairobi', 'Africa/Ndjamena', 'Africa/Niamey', 'Africa/Nouakchott', 'Africa/Ouagadougou', 'Africa/Porto-Novo', 'Africa/Sao_Tome', 'Africa/Tripoli', 'Africa/Tunis', 'Africa/Windhoek', 'America/Adak', 'America/Anchorage', 'Amer

In [129]:
tz = pytz.timezone('Asia/Seoul')

In [130]:
didx = pd.date_range('2020-01-01', periods=7, freq='B')
ts = pd.Series(np.random.randn(len(didx)), index=didx)
ts

2020-01-01   -0.484210
2020-01-02   -0.364146
2020-01-03   -0.566874
2020-01-06   -0.348180
2020-01-07   -0.896984
2020-01-08   -0.491758
2020-01-09    1.588265
Freq: B, dtype: float64

In [131]:
pd.date_range('2020-01-01 09:00', periods=7, freq='B', tz='UTC')

DatetimeIndex(['2020-01-01 09:00:00+00:00', '2020-01-02 09:00:00+00:00',
               '2020-01-03 09:00:00+00:00', '2020-01-06 09:00:00+00:00',
               '2020-01-07 09:00:00+00:00', '2020-01-08 09:00:00+00:00',
               '2020-01-09 09:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='B')

In [132]:
ts_utc = ts.tz_localize('UTC')
ts_utc

2020-01-01 00:00:00+00:00   -0.484210
2020-01-02 00:00:00+00:00   -0.364146
2020-01-03 00:00:00+00:00   -0.566874
2020-01-06 00:00:00+00:00   -0.348180
2020-01-07 00:00:00+00:00   -0.896984
2020-01-08 00:00:00+00:00   -0.491758
2020-01-09 00:00:00+00:00    1.588265
Freq: B, dtype: float64

In [133]:
ts_utc.index

DatetimeIndex(['2020-01-01 00:00:00+00:00', '2020-01-02 00:00:00+00:00',
               '2020-01-03 00:00:00+00:00', '2020-01-06 00:00:00+00:00',
               '2020-01-07 00:00:00+00:00', '2020-01-08 00:00:00+00:00',
               '2020-01-09 00:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='B')

In [135]:
ts_utc.tz_convert('Asia/Seoul')

2020-01-01 09:00:00+09:00   -0.484210
2020-01-02 09:00:00+09:00   -0.364146
2020-01-03 09:00:00+09:00   -0.566874
2020-01-06 09:00:00+09:00   -0.348180
2020-01-07 09:00:00+09:00   -0.896984
2020-01-08 09:00:00+09:00   -0.491758
2020-01-09 09:00:00+09:00    1.588265
Freq: B, dtype: float64

In [136]:
ts_seoul = ts.tz_localize('Asia/seoul')

In [137]:
ts_seoul.tz_convert('UTC')

2019-12-31 15:00:00+00:00   -0.484210
2020-01-01 15:00:00+00:00   -0.364146
2020-01-02 15:00:00+00:00   -0.566874
2020-01-05 15:00:00+00:00   -0.348180
2020-01-06 15:00:00+00:00   -0.896984
2020-01-07 15:00:00+00:00   -0.491758
2020-01-08 15:00:00+00:00    1.588265
dtype: float64

In [138]:
ts_seoul.tz_convert('Europe/Berlin')

2019-12-31 16:00:00+01:00   -0.484210
2020-01-01 16:00:00+01:00   -0.364146
2020-01-02 16:00:00+01:00   -0.566874
2020-01-05 16:00:00+01:00   -0.348180
2020-01-06 16:00:00+01:00   -0.896984
2020-01-07 16:00:00+01:00   -0.491758
2020-01-08 16:00:00+01:00    1.588265
dtype: float64

In [139]:
ts.index.tz_localize('America/New_York')

DatetimeIndex(['2020-01-01 00:00:00-05:00', '2020-01-02 00:00:00-05:00',
               '2020-01-03 00:00:00-05:00', '2020-01-06 00:00:00-05:00',
               '2020-01-07 00:00:00-05:00', '2020-01-08 00:00:00-05:00',
               '2020-01-09 00:00:00-05:00'],
              dtype='datetime64[ns, America/New_York]', freq=None)

In [140]:
stamp = pd.Timestamp('2020-01-01 12:00')
stamp_utc = stamp.tz_localize('UTC')
stamp_utc

Timestamp('2020-01-01 12:00:00+0000', tz='UTC')

In [141]:
stamp_utc.value

1577880000000000000

In [142]:
stamp_utc.tz_convert('Asia/Seoul')

Timestamp('2020-01-01 21:00:00+0900', tz='Asia/Seoul')

In [143]:
stamp_utc.tz_convert('Asia/Seoul').value

1577880000000000000

In [150]:
stamp_ny = pd.Timestamp('2020-01-01 12:00', tz='America/New_York')
stamp_ny

Timestamp('2020-01-01 12:00:00-0500', tz='America/New_York')

In [151]:
stamp_ny.value

1577898000000000000

In [146]:
stamp_utc.tz_convert('Asia/Shanghai')

Timestamp('2020-01-01 20:00:00+0800', tz='Asia/Shanghai')

In [153]:
stamp = pd.Timestamp('2020-01-01 12:00', tz= 'Asia/Seoul')
stamp

Timestamp('2020-01-01 12:00:00+0900', tz='Asia/Seoul')

In [154]:
from pandas.tseries.offsets import Hour
stamp + Hour()

Timestamp('2020-01-01 13:00:00+0900', tz='Asia/Seoul')

In [155]:
stamp + 3 * Hour()

Timestamp('2020-01-01 15:00:00+0900', tz='Asia/Seoul')

In [156]:
ts_utc

2020-01-01 00:00:00+00:00   -0.484210
2020-01-02 00:00:00+00:00   -0.364146
2020-01-03 00:00:00+00:00   -0.566874
2020-01-06 00:00:00+00:00   -0.348180
2020-01-07 00:00:00+00:00   -0.896984
2020-01-08 00:00:00+00:00   -0.491758
2020-01-09 00:00:00+00:00    1.588265
Freq: B, dtype: float64

In [158]:
ts1 = ts_utc[:5].tz_convert('Europe/Berlin')
ts2 = ts_utc[2:].tz_convert('America/New_York')
ts = ts1 + ts2

In [159]:
ts.index

DatetimeIndex(['2020-01-01 00:00:00+00:00', '2020-01-02 00:00:00+00:00',
               '2020-01-03 00:00:00+00:00', '2020-01-06 00:00:00+00:00',
               '2020-01-07 00:00:00+00:00', '2020-01-08 00:00:00+00:00',
               '2020-01-09 00:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='B')

### 기간과 기간 연산

In [160]:
p= pd.Period(2020, freq='A-JAN')
p

Period('2020', 'A-JAN')

In [161]:
p + 2

Period('2022', 'A-JAN')

In [162]:
p - 3

Period('2017', 'A-JAN')

In [164]:
p1 = pd.Period(2010, freq='A-JAN')
p2 = pd.Period(2020, freq='A-JAN')
p2 - p1

<10 * YearEnds: month=1>

In [165]:
pr = pd.period_range('2020-01-01', '2020-06-30', freq='M')

In [166]:
pd.Series(np.random.randn(6), index=pr)

2020-01    1.024047
2020-02    0.816610
2020-03   -0.178974
2020-04   -0.047391
2020-05   -0.451397
2020-06    0.811403
Freq: M, dtype: float64

In [167]:
pidx =pd.PeriodIndex(['2020-1', '2020-2', '2020-4'], freq='M')
pidx

PeriodIndex(['2020-01', '2020-02', '2020-04'], dtype='period[M]', freq='M')

In [168]:
p = pd.Period('2020', freq='A-FEB')
p

Period('2020', 'A-FEB')

In [169]:
p.asfreq('M', how='start')

Period('2019-03', 'M')

In [170]:
p.asfreq('m', how='end')

Period('2020-02', 'M')

In [171]:
p = pd.Period('2020', freq='A-OCT')
p

Period('2020', 'A-OCT')

In [172]:
p.asfreq('M', how='end')

Period('2020-10', 'M')

In [173]:
p = pd.Period('2020Q2', freq='Q-JAN')
p

Period('2020Q2', 'Q-JAN')

In [174]:
p.asfreq('D', 'start')

Period('2019-05-01', 'D')

In [175]:
p.asfreq('D', 'end')

Period('2019-07-31', 'D')

In [177]:
pr = pd.period_range('2019Q3', '2020Q3', freq='Q-JAN')
ts = pd.Series(np.arange(len(pr)), index=pr)
ts

2019Q3    0
2019Q4    1
2020Q1    2
2020Q2    3
2020Q3    4
Freq: Q-JAN, dtype: int32

In [181]:
pr = pd.date_range('2019Q3', periods=5, freq='Q-JAN')
ts = pd.Series(np.random.randn(5), index=pr)
ts

2019-07-31    0.221508
2019-10-31    2.016662
2020-01-31   -0.775075
2020-04-30   -0.311983
2020-07-31   -1.676341
Freq: Q-JAN, dtype: float64

In [182]:
ts.to_period()

2020Q2    0.221508
2020Q3    2.016662
2020Q4   -0.775075
2021Q1   -0.311983
2021Q2   -1.676341
Freq: Q-JAN, dtype: float64

In [183]:
pr = pd.date_range('2020-01-01', periods=5, freq='D')
ts = pd.Series(np.random.randn(5), index=pr)
ts

2020-01-01   -0.172196
2020-01-02   -2.867326
2020-01-03   -1.258521
2020-01-04    0.140224
2020-01-05   -0.514933
Freq: D, dtype: float64

In [185]:
p = ts.to_period('M')
p

2020-01   -0.172196
2020-01   -2.867326
2020-01   -1.258521
2020-01    0.140224
2020-01   -0.514933
Freq: M, dtype: float64

In [186]:
p.to_timestamp(how='start')

2020-01-01   -0.172196
2020-01-01   -2.867326
2020-01-01   -1.258521
2020-01-01    0.140224
2020-01-01   -0.514933
dtype: float64

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly